# Etapa 1: builder
FROM python:3.11-alpine AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 2: final
FROM python:3.11-alpine

WORKDIR /app

# Copiar solo lo necesario
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY app.py .

EXPOSE 5000

CMD ["python", "app.py"]